### ISSUE TITLE
How to report/log errors?

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#115]
How do we handle errors consistently? In a couple of places these are displayed through `donsole.log` for debugging but for production code this is maybe not the best way. Errors that have an effect to the user should go to `AlertService` but some logging is only relevant for debugging - do we log them at all?

This is related to #38 (transmitting error logs to server for analysis by the dev team).

**Comment by sleidig** [comment]
We could maybe add another Alert level "SILENT" or "DEBUG" that will not display a message but log to the console and the persistent app log for debugging when necessary.

**Comment by codingfabi** [comment]
Adding another Alert level sounds good. Maybe call it "debug" or "dev" or something.

**Comment by sleidig** [comment]
I am adding an Alert type `Alert.DEBUG` and replacing all `console.log()` calls in the code to use `alertService.addDebug()` (or a different alert level).

**Comment by sleidig** [comment]
Documentation for this: https://github.com/NGO-DB/ndb-core/wiki/Logging-errors-and-other-information
