### ISSUE TITLE
Import data from CSV

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#117]
To take the app into practical use, we have to be able to import existing data into our database. The easiest, most flexible format for now is probably CSV.

**Comment by Lorsbyjm** [comment]
@SuppenGeist I assigned you cause it looks like a feature you could look into. Let's talk about it tomorrow in the meeting.

**Comment by sleidig** [comment]
sorry, didn't update this issue. I'm almost done with this already.

**Comment by sleidig** [comment]
further extension of this in #126 . @SuppenGeist, maybe you wanna look into that?
