### ISSUE TITLE
UI to comfortably add monthly attendance data

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#137]
Attendance data is usually collected for all students of a school (or of a center) each month. Rather than editing each individual Child's records, an optimized UI is required to quickly enter a batch of `AttendanceMonth` records.

- accessed from SchoolDetails page of a school
- form header allows input of: month, daysWorkding of that month for that school
- form further shows table of all current students of that school with input fields for his/her daysPresent, daysExcused, remarks
- form save button creates/saves the whole batch of `AttendanceMonth` records of these students

**Comment by Lorsbyjm** [comment]
#138 seems to be en envolvment of this.

**Comment by sleidig** [comment]
This is probably still useful in addition to #138 (daily attendance data) as an alternative UI. In some cases daily data may not be available for users (e.g. when only collecting attendance data from a school once at the end of the month). So a comfortable way to add summarized monthly data is an alternative use case.

**Comment by sleidig** [comment]
closing with PR #158
