### ISSUE TITLE
Manage daily attendance data

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#138]
Rather than adding attendance statistics only after a completed month, real-time information would be much more helpful. A user should be able to add a single day's attendance data and display the attendance in a well visualized calendar layout.

- [x] Entity type AttendanceDay and/or adaption of `AttendanceMonth` to aggregate a month's daily attendance and always calculate the current percentage of attended days
- [x] UI to display daily attendance well visualized for analysis
- [x] integrate daily attendance view at relevant sections of the app
- [ ] extend UI of monthly attendance (`AddMonthAttendanceComponent`) to allow displaying/editing a group's daily attendance
- [x] UI (mobile first!) for teacher to easily take attendance directly on smartphone in the classroom for a section of students (of a school / center / other filter)
- [x] add Dashboard widget to display last weeks absences

**Comment by codingfabi** [comment]
Is this done with PR #158 ?

**Comment by sleidig** [comment]
No, this is an additional extension of the feature. PR #158 / Issue #137 makes bulk entry of monthly data easier, while this here will extend the feature to enter attendance data on a daily basis. Both are useful features (see https://github.com/NGO-DB/ndb-core/issues/137#issuecomment-403202717)
