### ISSUE TITLE
Child photo

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#141]
allow for upload (or link from NextCloud?!) of a photo for Child and display it instead of the current placeholder picture.

**Comment by Lorsbyjm** [comment]
#89Handling/StoringFiles

**Comment by Lorsbyjm** [comment]
#89 see this as idea of storing files

**Comment by sleidig** [comment]
I am implementing the UI side of this quickly, with hard-coded linking to pictures of the server. As new team members are joining next week, the pilot version would benefit a lot from displaying the children's photos.
A scalable solution to manage the photo files (-> #89) as well as a UI to upload/change photos would still be pending after closing this issue.
