### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#142]
A frequent use case is that a user filters the children list (e.g. for a specific center or school) and then checks or edits the details of each child. A back button, leading from the child details page back to the children list with previously selected filters is therefore requested. At the moment, users have to take several steps, setting the filters on the children list anew every time.

- [x] Add button to go back in browser history to UI
- [x] Encode filters applied to ChildrenList in the URL
- [x] Encode filters applied to SchoolsList in the URL (?)
- [x] Change links of `ChildrenCountDashboardComponent` to use the "center" filter URL instead of the free text filter

**Comment by codingfabi** [comment]
How should this be implemented? Maybe store active filter values in the url as parameters so routing via the back button is easy? any other ideas?

**Comment by sleidig** [comment]
Yes, I would also suggest keeping all filtering in the URL. Then the browser's back button (or javascript function) would do the trick.

**Comment by codingfabi** [comment]
im trying to implement this in the "back_button_feature" branch.
I managed to save the filter selection for the dropout filter, but the filter for the center list keeps on dissapearing. Im getting a ""ExpressionChangedAfterItHasBeenCheckedError" exception and cant find a way to fix it. I cant make sense out of any tutorials I found after googleing this error. So maybe someone could have a look at this? @sleidig @TheSlimvReal ?

Full ErrorMessage:
_ERROR Error: "ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'value: Berlin'. Current value: 'value: All'."_

**Comment by sleidig** [comment]
uff, in the end the problem seems to be with the two-way databinding of `[(value)]` ... but I don't really understand why. I found a workaround, however. 

And in the process of poking around for hours, I also generalized the whole filter selection logic, so it can easily be configured and reused.

see #149

**Comment by codingfabi** [comment]
That two-way databinding was what got me wondering too. lets stick with the Workaround for now, as Long as it works.

**Comment by sleidig** [comment]
can you also update the links of ChildrenCountDashboardComponent to use the "center" filter URL instead of the free text filter?

**Comment by codingfabi** [comment]
done, pr should be ready

**Comment by codingfabi** [comment]
closed with pr #149
