### ISSUE TITLE
Update (ServiceWorker) notification or reload

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#148]
When a new version is loaded to the server, users still see the old app as it is cached using `@angular/pwa`. It seems the user actually has to do a had reload (Ctrl + F5) to get the update.

Users should receive a notification when there is a new version on the server with a link to load/refresh to get the update.

It seems like Service Workers offer some functionality to achieve this: https://angular.io/guide/service-worker-communications#swupdate-service

**Comment by sleidig** [comment]
Any progress here or shall I take this up?

**Comment by Lorsbyjm** [comment]
You can take it, markus has not ben there for a while

**Comment by Lorsbyjm** [comment]
Any further comments on that or should we take away High Priority?
