### ISSUE TITLE
ChildrenList sorting not working

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#150]
In the ChildrenList clicking on the table column headers should sort the whole list. However, this seems to only change the order of the first two rows of the table.

**Comment by codingfabi** [comment]
I can't reproduce the bug. Sorting seems to work just fine, except for the age coloumns. In this coloumn, it doesn't work at all. 
In the master branch, when you sort after name, it sorts lower case latters prioritized, which is not a bug i think. We could fix this by forcing the first letter of every child name to be upper case.
The age coloumn however doesnt sort at all. I think the Problem could be something with synchronization of the ngAfterViewInit():

`ngAfterViewInit() {
    this.childrenDataSource.sort = this.sort;
  }`

**Comment by sleidig** [comment]
Sorry, you are right. Sort is working for names and project numbers - but is broken for class and school columns.

Class may have problems because we save it as strings rather than numbers, so the sort order may be not intuitive. But what's actually happening is that only the first 2-3 lines change order and the rest of the table remains static.

**Comment by sleidig** [comment]
I got to the root of the problem: `matColumnDef` and the property name of the model entity need to match (e.g. for `child.schoolClass` it has to be `matColumnDef="schoolClass"` rather than `matColumnDef="class"`). see https://stackoverflow.com/a/48509392/1473411
