### ISSUE TITLE
Show child picture on childListUI?

### ISSUE THREAD

**Issue by codingfabi** [NGO-DB/ndb-core#155]
Are we planning on showing a small preview of the childs photo on the childlist dashboard? 
I don't think that this is helpfull to be honest. The pictures are to small to recognize a child in my opinion and i doubt that social workers will find the child they're looking for by a picture.

**Comment by sleidig** [comment]
I would put the passport size picture into the summary overlay (on hovering the mouse), and of course on the ChildDetails page. 
Whether the small picture that is currently the placeholder face will be of any use with the actual photos I am not sure. Let's see how it comes out once we have pics. Alternatively we could replace it there by a child symbol. But even the small photo might be a useful clue to distinguish different kids (we have two pairs of kids with the exact same first and last names here, for example).

**Comment by codingfabi** [comment]
Okay passport size picture seems to be actually helpfull in the live system.
Do you want to show each individual picture in the list?
If not, I would suggest a different thumbnail for boys and girls.

**Comment by codingfabi** [comment]
Can be closed.
