### ISSUE TITLE
Search checks match in name and id

### ISSUE THREAD

**Issue by Lorsbyjm** [NGO-DB/ndb-core#157]
![searchbug](https://user-images.githubusercontent.com/9371498/43293590-5f69fbca-913b-11e8-8295-bd0d3864b8e1.PNG)

**Comment by sleidig** [comment]
It's not a bug, it's a feature ;-)

Although nowadays, with IDs completely randomized, it doesn't make as much sense. The id is still visible to the user in the URL though, so there is a use case where users remember (part of) the id and want to search for it. More practical is probably allowing search for the project number.
