### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#16]
The project doesn't have any license at the moment. We agreed to make this Open Source but there still are a few choices about the specific license to pick.

Helpful resources:
- Comparison of licenses with main points summarized: [choosealicense.com](http://choosealicense.com/)
- Overview and discussion of different aspects: [Guide to choosing an open-source license](https://opensource.com/law/13/1/which-open-source-software-license-should-i-use)

Other Open Source projects are using:
- Angular 2: _MIT License_
- PouchDB: _Apache License_
- Drupal (CMS): _GPL_
- Wordpress: _GPL_
- LibreOffice: _Mozilla Public License_

The libaries we are using (Angular, PouchDB) are licensed permissively so we don't have limitations on our license here.

**Comment by sebastian-leidig** [comment]
It comes down to the choice between "strict" Open Source (GPL) or also allowing our code to be used in projects with a different license, so it can be picked up more easily (e.g. MIT license).

**Comment by fschoell** [comment]
Another thought that crossed my mind just now: We could use MIT for the ndb-core project and GPL for the actual implementations. This way we would be able to create a proprietary project based on ndb-core if we ever wanted to, but nobody could "steal" our actual projects.

**Comment by sleidig** [comment]
The decision about a license won't get easier after more and more people joined the team again. I only go by simple heuristics here but:
As our software is somewhat like a CMS (Drupal, Wordpress) and I am fond of "real" Open Source, I suggest we just go with GPL.

What do you say? @fschoell @ojauch ?

**Comment by fschoell** [comment]
Agree. The GPL prevents us from running into license incompatibilities with 3rd party libraries, too.

**Comment by sleidig** [comment]
closed through PR #57
