### ISSUE TITLE
Upgrade Angular to RC4

### ISSUE THREAD

**Issue by sebastian-leidig** [NGO-DB/ndb-core#18]
Angular 2 has a new version RC3 released. We are currently using RC1.

Especially the Router system seems to have changed. We should check and possibly rework this in our code: https://angular.io/docs/ts/latest/guide/router.html

**Comment by fschoell** [comment]
RC4 has been released in the meantime

**Comment by sebastian-leidig** [comment]
The upgrade itself is done now see 85bee78867aac23d0a9b92d755dfc14df3c63071

This includes adaptions to the routing to use angular's new router system. Any further improvements to the design of our navigation system overall should be discussed in #7 .

Some warning still remains:
> *It looks like you're using the old forms module. This will be opt-in in the next RC, and
      will eventually be removed in favor of the new forms module. For more information, see:
      https://docs.google.com/document/u/1/d1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub

**Comment by fschoell** [comment]
Anleitung fürs forms Upgrade: https://stackoverflow.com/questions/37871271/how-to-migrate-angular-2-rc-1-or-earlier-forms-to-angular-2-rc-2-rc-4-new-fo/37902014#37902014
