### ISSUE TITLE
Back navigation

### ISSUE THREAD

**Issue by jana47** [NGO-DB/ndb-core#191]
When you navigate to the children list and then try to navigate back to the last viewed page in your browser, you will stay in the children list.

**Comment by liwde** [comment]
When we enter the route `/child`, at `loadData` `this.router.navigate()` is called to add the parameters to the URL, resulting in the navigation to be added to the history. A simple back-navigation in history will result in `/child` being accessed, again `navigate`ing to the URL with the parameters again.

With the `replaceUrl` option, the router will change the URL *without* adding to this history. This way, back-navigation will work again.
