### ISSUE TITLE
Bug on branch fx-layout (resize dashboard)

### ISSUE THREAD

**Issue by jana47** [NGO-DB/ndb-core#196]
When you start the app, navigate to the children list and then back to the dashboard and then resize the app (make it smaller), the app automatically navigates back to the children list.

(Only on branch fx-layout!)

**Comment by jana47** [comment]
[https://github.com/NGO-DB/ndb-core/tree/fx-layout](url)

**Comment by LukkyLukke** [comment]
Can confirm

**Comment by Lorsbyjm** [comment]
Can you please check if this goes along with #215. I think it is caused by the same reason.

**Comment by jana47** [comment]
I think so, too. I commented l. 62-64 in children-list.component.ts out. If you do that, you can resize the dashboard without being navigated back to the children list and also you can click on a child and get to the child details.

**Comment by Lorsbyjm** [comment]
OK, I looked into it. The problem ist that we have an table type "mobile" that will be stored in the url as parameter. 
This is not the way to rezise the table. The table itself has to react to the shrinking size, we can not set it as url parameter.

**Comment by Lorsbyjm** [comment]
Solved it by adding an onDestroy method to the childrenslist component, in which the watcher is unsubscribed from the mediaQuery, so there is no reaction towards the changing screensize anymore.
