### ISSUE TITLE
Alerts Module

### ISSUE THREAD

**Issue by sebastian-leidig** [NGO-DB/ndb-core#2]
> **Components need to register `Alert`s that are displayed hovering on the top right part of the screen.**

Currently this is done with our `AlertManager` and `AlertCtrl`.

We can probably just reimplement these as a Service and Component in Angular2. Displaying may pose a challenge, as `angular-bootstrap` is not ready for Angular2.

**Comment by sebastian-leidig** [comment]
Thanks @ojauch!

The only thing left to do is some visible UI element hinting that you can discard alerts by clicking on them.

**Comment by ojauch** [comment]
@sebastian-leidig I think the [ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap) would be a good choice for this issue, because it provides angular 2 directives for bootstrap components like alerts. Maybe we should use prefixes for our typescript classes, because I'm running into naming issues when I want to use the alert module of ng2-bootstrap.

**Comment by sebastian-leidig** [comment]
ng2-bootstrap sounds good. for helgo_db we had used [angular-ui bootstrap](https://github.com/angular-ui/bootstrap#angular-2), that is working on an Angular2 version in [a different repo](https://github.com/ng-bootstrap/core). I am a little confused which one is the best choice for us right now.

About the naming issues: Maybe we can fix that somehow using namespaces? e.g. importing the external library as a different alias? http://stackoverflow.com/a/19758638/1473411
It would be nice to keep our class names as simple as possible of course.

**Comment by ojauch** [comment]
I just found out that the naming isn't an issue anymore and the README of ng2-bootstrap was just outdated. But the idea of using namespaces in the future sounds nice.

**Comment by sebastian-leidig** [comment]
Great, I think this is done now.
