### ISSUE TITLE
Bug in demo-data.ts (only occurs in March)

### ISSUE THREAD

**Issue by liwde** [NGO-DB/ndb-core#232]
In March, demo-data.ts will create attendance-information for February. It assumes that numbering of days starts at 1 (as is the default in JavaScript):

```ts
    current1.dailyRegister[1].status = AttendanceStatus.PRESENT;
    current1.dailyRegister[2].status = AttendanceStatus.PRESENT;
//...
    current1.dailyRegister[27].status = AttendanceStatus.PRESENT;
    current1.dailyRegister[28].status = AttendanceStatus.LATE;
```

However, AttendanceMonth.updateDailyRegister() creates the `dailyRegister` with indices starting at 0 (because array.push() is used). Therefor, `dailyRegister[28]` is undefined and its `.status` cannot be set.

@sleidig, is this an issue with the demo data and all indices should be reduced by 1, or should the dailyRegister behave differently?

**Comment by sleidig** [comment]
Good find. Looking at this, I should maybe rewrite some stuff of the AttendanceMonth class. Looks awfully messy ...

AttendanceMonth.dailyRegister is just an Array and should indeed start with indices at 0. I think changing that would screw us in a lot of the loops we have to analyse over its data. We should probably add a warning about the index in a comment, though.

I guess the actual day of a `AttendanceDay` object in the `dailyRegister` should be retrieved with something like `dailyRegister.find(d => d.date.getDate() === searchedDate.getDate())`
