### ISSUE TITLE
Entity-subrecord implementations content sorting fail when value is undefined

### ISSUE THREAD

**Issue by christophscheuing** [NGO-DB/ndb-core#244]
Implementations of the entity subrecord component fail to show content when the value of the colum relevant for sorting doesn't contain any value.

This is also a problem in the master branch.

Example from the health checkup component:

`  loadHealthChecks() {
    this.childrenService.getHealthChecksOfChild(this.childId)
      .subscribe(results => {
        this.records = results
          .sort(( a, b ) => b.date.valueOf() - a.date.valueOf())
      });
  }`

**Comment by christophscheuing** [comment]
Possible solution that works for the previous school component:

`.sort((a, b) => (b.start?b.start.valueOf():0 - (a.start?a.start.valueOf():0)));`

Should this be generalized to the other components sorting by date?

**Comment by codingfabi** [comment]
This was fixed with PR248
