### ISSUE TITLE
Continuous Integration & Delivery

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#25]
Now that we have unit tests working ( #22 ), it would be great to set up continuous integration and continuous delivery, so we get a demo of the latest master branch automatically deployed and tested.

**Comment by fschoell** [comment]
We should take a look into [Travis CI](https://travis-ci.org/) to automatically execute the tests and maybe `tslint`. Deployment should be possible, too.

**Comment by sleidig** [comment]
@fschoell If you like, I am happy to get support on the infrastructure part. Send me a message and I'll create an account for you on the server.

**Comment by fschoell** [comment]
Okay, I'll take a look into it. I've created a github account which we can use for the Travis authorization etc. Could you add the [account](https://github.com/ndbbot) to the NGO-DB organization?

**Comment by sleidig** [comment]
see #41

**Comment by sleidig** [comment]
CI is merged now.

@fschoell did you already have a look at continuous delivery?

**Comment by fschoell** [comment]
Yes, that's pretty straightforward. We can configure Travis to execute a production build and deploy the results to a server either using FTP or SCP, if the commit is tagged (as release) and happened on the master branch. 
However, the build status is not affected by the deployment, so we won't notice if a deployment fails. I think we should discuss a strategy on the next meeting.

**Comment by fschoell** [comment]
Moved it to Ideas as long as we don't have regular releases this isn't really important.

**Comment by sleidig** [comment]
Travis CI now deploys the built angular app if a commit is tagged in git. The 'dist' package is published as a download on the [GitHub Releases page](https://github.com/NGO-DB/ndb-core/releases) and a new docker container is built and published to [Docker Hub](https://cloud.docker.com/u/aamdigital/repository/docker/aamdigital/ndb-server) and can be easily deployed through this.
