### ISSUE TITLE
Added Alerts not displayed

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#33]
When adding an alert to the `AlertService`, the alert is successfully added to the array (tested using by writing it to console) but the alert message is not displayed in the UI.

**Comment by fschoell** [comment]
Is there a way to reproduce this? Alerts I've added while implementing the latest changes module have been shown on the UI.

**Comment by sleidig** [comment]
This problem was coming up in the ndb-sample project. Between modules in ndb-core it seems to work fine.

We have to figure out how to include ndb-core into ndb-sample again with the new project setup from angular2-seed. Can't test it right now because of this.

**Comment by Lorsbyjm** [comment]
@sleidig This seems to be old. Still needed?

**Comment by sleidig** [comment]
Let's close for now. Bug may be fixed with all the changes that happened since then.
