### ISSUE TITLE
Upgrade Angular to RC6

### ISSUE THREAD

**Issue by sebastian-leidig** [NGO-DB/ndb-core#34]
A new release candidate was published: https://angularjs.blogspot.de/2016/09/angular-2-rc6_1.html

Upgrade shouldn't break anything for us, as far as I see from a quick check

**Comment by sebastian-leidig** [comment]
`npm test` is broken (finding 0 tests)

it warns

> 404: /base/node_modules/@angular/core/testing.js

which is probably related to the `karma-test-shim.js`

**Comment by fschoell** [comment]
Closing this in favor of #36
