### ISSUE TITLE
Transmit error logs to server

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#38]
For debugging and monitoring it would be helpful to automatically or easily send logs from a browser to the server, so developers can analyse the problem.

**Comment by Lorsbyjm** [comment]
@mspoeri  is the tool you want to use for logging capable to solve this issue? 
Then we could merge the issues

**Comment by sleidig** [comment]
@mspoeri can you give a short comment why you are choosing [sentry.io](https://sentry.io)?

**Comment by sleidig** [comment]
closed with PR #147
