### ISSUE TITLE
Can we agree on a code format?

### ISSUE THREAD

**Issue by fschoell** [NGO-DB/ndb-core#39]
I don't care how we format the code, but it's annoying to resolve merge conflicts because of different formats. 

@sleidig You're using a different code format from the default one (spaces within the import statements). Should we make this a global rule (I'm fine with it)? Is this the only change you made to the code formatter?

**Comment by sleidig** [comment]
Absolutely agree, sorry about inconsistencies.

Personally, I think `import { Alert } from './alert';` is nicer to read with spaces in the braces, but it may well be easier to just agree on the default code format. Shall we stick with standard webstorm formating?

**Comment by sleidig** [comment]
Another point regarding code style is `"` vs. `'`.

Our current lint configuration (copied from angular2-seed) complains
> "  should be  '
 
I changed this for most code but some cases tend to come back.

**Comment by fschoell** [comment]
This is the auto importer from Intellij but it's possible to change it to single quotes. I agree that import statements with spaces are nicer to read.

As we all are using IntelliJ we simply could add a codestyle.xml to the repository with those two rules. If someone ever switches the IDE he probably has to adapt the code style rules anyways as the default options probably aren't the same as those from IntelliJ.

**Comment by sleidig** [comment]
added a `code-style.xml` to the repository root containing those two issues we brought up.

This can be imported in WebStorm under `File | Settings | Editor | Code Style` by clicking the `Manage ...` button left of the "Scheme" selector.


Feel free to propose additional or different code style issues though!

**Comment by fschoell** [comment]
Closing it for now
