### ISSUE TITLE
Create / Use Mock Services for Tests

### ISSUE THREAD

**Issue by fschoell** [NGO-DB/ndb-core#49]
The latest changes module for example does http calls in the test specs. That should not happen, but rather be replaced by some mock services like [this](http://stackoverflow.com/questions/39472364/testing-cant-resolve-all-parameters-for-classname/39483673#39483673).

**Comment by sleidig** [comment]
We are not using any external Services like `HttpClient` in any of our tests (anymore?). 
Whenever we improve unit tests, we should look to isolate them more and more from services like the big `EntityMapperService`. It's often easier to test when mocking these to inject relevant test data.

**Comment by sleidig** [comment]
A sample for possible mocks of Services:

Provide an instance of the Service to be mocked, while ignoring any dependencies further down:
```
  let childrenService: ChildrenService;

  beforeEach(async(() => {
    childrenService = new ChildrenService(null); 
    // don't inject dependencies all through the hierarchy, we'll mock the actual function calls with spyOn

    TestBed.configureTestingModule({
      declarations: [MyComponent],
      // import needed modules but avoid that if a service can simply be mocked
      imports: [MatIconModule],
      providers: [
        {provide: ChildrenService, useValue: childrenService},
      ]
    })
      .compileComponents();
  }));
```
Then use `spyOn` to mock a return value (and avoid errors from undefined dependencies):
```
it('should count children correctly', (done) => {
    spyOn(childrenService, 'getChildren').and
      .returnValue(Observable.of([new Child('1'), new Child('2')]);
    
    component.loadAndCountChildren()
      .subscribe((result) => {
        expect(component.childCount).toBe(2);
        done();
      });
  });
```
