### ISSUE TITLE
Dashboard Module

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#5]
> **The user should see have a page to see an overview of different sections of the app.
> (In the future this could also include dynamic content like reminders or statistics)**

Previously this was a hard-coded template.

Things to consider:
- How can other modules/apps extend this? (e.g. an "HELGO DB" app that is based on this "ndb-core")
  - Dynamically load and display some kind of "widgets" that are provided through a separate Service?

**Comment by ojauch** [comment]
Maybe we could provide some kind of slots on the dashboard (e.g. sidebar, main view, etc.) where widgets could be registerd. Or do you think about a more generic service where the position of the widgets is fully customizable?

**Comment by sebastian-leidig** [comment]
For now I would also keep it simple. If we go with a fixed layout with slots, we can focus on the question how to dynamically add components to the Dashboard.

(maybe the "widgets" stay something like the colored panels on the "Overview" page of the old version)

**Comment by sebastian-leidig** [comment]
We postpone this feature for now. Apps built on ndb-core can implement a complete DashboardComponent themselves.

Once we have a "real" app working, we can look at its dashboard and think about how to factor out common functions.

**Comment by sleidig** [comment]
With PR #118 the first widgets are implemented and useable.
I am closing this issue now after having opened two new issues regarding the further extension of this:
- allow users to reorder/remove/add widgets dynamically (see #119)
- design a system for modules to register widgets with the DashboardModule without the DashboardModule explicitly importing and displaying every widget manually (see #120)
