### ISSUE TITLE
Fix Travis CI

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#50]
currently Travis fails with the error

> ... 'apply' of undefined ...

**Comment by fschoell** [comment]
The tests will run locally however, so this is probably more likely an issue with the travis config than the actual test cases.

**Comment by fschoell** [comment]
Now it's failing completely. Not sure what the problem is. Everything fails on the current pull request (see [here](https://travis-ci.org/NGO-DB/ndb-core/jobs/250016295)). However, locally it's running fine.
