### ISSUE TITLE
Remove jquery dependency?

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#53]
Why do we need `jquery`? This is currently included as a dependency in our [package.json](https://github.com/NGO-DB/ndb-core/blob/master/package.json#L27).

Was this included for bootstrap? Then it should not be needed anymore as [ngx-bootstrap](https://github.com/valor-software/ngx-bootstrap) takes care of that within Angular only.

@fschoell Do you have any idea where this might be needed?

Otherwise, let's try to remove it and see what happens.

**Comment by fschoell** [comment]
Okay let's see, I'll try it

**Comment by sleidig** [comment]
removed and closed with PR #56
