### ISSUE TITLE
"AlertsComponent" error: 'type' isn't known property of 'alert'

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#55]
When running the unit tests (`ng test`) I get the following error with a failed test of `AlertsComponent`:

> Can't bind to 'type' since it isn't a known property of 'alert'. ("<alert *ngFor="let alert of alerts" [ERROR ->][type]="alert.type" dismissible="true" (close)="deleteAlert(alert)">
  {{ alert.message }}
</alert>

Seems like something is not working with the [ngx-bootstrap alerts](http://valor-software.com/ngx-bootstrap/#/alerts). It might be a name confusion because we also have a local component in our project named "alert".

**Comment by fschoell** [comment]
Problem was that the AlertModule from the ngx-bootstrap package wasn't imported into the AlertsComponent test class. Fixed it in #56

**Comment by sleidig** [comment]
How did I spend an hour tinkering on this without finding the solution? ;-)

**Comment by sleidig** [comment]
fixed with PR #56
