### ISSUE TITLE
LatestChangesModule error: 404 not found

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#58]
The changelog cannot be loaded and the JavaScript console shows 
> 404 Not Found - http://localhost:4200/app/changelog.json"

Also, the LatestChangesModule had some failing unit tests (run `ng test` to see):

> LatestChangesService should be created
Error: No provider for Http!

> LatestChangesComponent should be created
Failed: Template parse errors:
There is no directive with "exportAs" set to "bs-modal" ("
</div>

**Comment by aankitkumar31** [comment]
404 Not Found - http://localhost:4200/app/changelog.json" issue is fixed actually there is no file named with changelog.json and the path is given wrong in latest-changes

**Comment by sleidig** [comment]
closed by #74
