### ISSUE TITLE
Fix broken unit tests

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#59]
A number of unit tests were failing and have been disabled in commit 9c3b054.

All those tests should be revised, repaired and activated again. If any of the tests seem useless, they should be removed completely rather than keeping them commented in the code. Also, it might be useful to add some additional unit tests for these modules.

- [x] LatestChangesService - should be created
- [x] LatestChangesComponent - should be created
- [x] NavigationComponent - should be created
- [x] LoggedInGuard - should ...
- [ ] ~~~LoginComponent - should be created~~~ (as part of #78)
- [x] SessionService - is logged in after correct local login
- [x] SessionService - is logged in on remote database after correct login
- [x] SessionService - is not logged in after failed local login on existing user
- [x] SessionService - is not logged in even when remote login succeeds
- [x] SessionService - is not logged in after logout
- [x] SessionService - can logout when not logged in
- [x] SyncStatusComponent - should be created
- [x] UiComponent - should be created
- [x] UserAccountComponent - should be created
- [x] User - has ID with correct prefix
- [x] User - accepts valid password
- [x] User - rejects wrong password

**Comment by fschoell** [comment]
Often because they are missing some imports. However, we shouldn't just import every service, but rather create or use existing mock services. See #49

**Comment by sleidig** [comment]
With PR #121 all the deactivated unit tests of above components are active and the `imports: []` problems fixed. While some Modules would benefit from more extensive unit tests, that's probably beyond the scope of this issue here. All Components at least have a `.spec.ts` file with at least one working test as a starting point.
Our aim should be to increase overall test coverage of the project. Current stats can be seen here: https://codeclimate.com/github/NGO-DB/ndb-core
