### ISSUE TITLE
Use a comprehensive logging service 

### ISSUE THREAD

**Issue by fschoell** [NGO-DB/ndb-core#60]
console.log  isn't suitable for larger projects. We should use a 3rd party logging library to improve our logs. 

Tasks:
 - [ ] Research a suitable logging library for angular (angular2-logger might suit us). Take #38 into account there, too. 
 - [ ] Include the library into the project and replace console.log with the new logging library and suitable log levels.

**Comment by Lorsbyjm** [comment]
@mspoeri This looks like you are working on this already, right?

**Comment by sleidig** [comment]
All logging (and related user notification) is exclusively done through our `AlertsModule` nowadays. Integration of a logging service and a possible sharing of logs with developers (see #38) should extend that module only.

**Comment by mspoeri** [comment]
@sleidig 

Your approach implies that logs and alerts are equal, which is wrong since not all alerts should be logged and not all logs should trigger an alert. 

So I want to introduce a separate logging service that is used by the alert service and can also be used within the application for pure logging requests.

**Comment by sleidig** [comment]
True, logging and alerts/notifications should not be exactly the same. Maybe all (or most?) alerts should be logged as well but not all log messages should be notified in the UI (this is already prevented with the Alert type `Alert.DEBUG`). It would probably be cleaner to have to separate modules for each, which may use each other if necessary.

**Comment by sleidig** [comment]
closed with PR #147.
The issue of distinguishing between notifying user and logging alerts maybe has to be revisited when the logging data increases
