### ISSUE TITLE
Choose table module/library

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#62]
We previously used [ng-table](http://ng-table.com/) (for AngularJS 1) to display dynamically sortable/filterable lists of children/schools/etc.

Such a library/module should make it easy for us to display arrays of data (class instances) and interact with it, without having to implement standard functionality, like different ways to sort it, ourselves.

What should we use as a library/module now?
What are the alternatives?

**Comment by sleidig** [comment]
One option would be https://github.com/valor-software/ng2-table

**Comment by aankitkumar31** [comment]
i would suggest to use https://www.npmjs.com/package/angular2-datatable

**Comment by sleidig** [comment]
Please give us a little more info:
Pro: What does it provide? Why would you prefer it?
Con: What does it not offer that alternatives are offering?

**Comment by aankitkumar31** [comment]
pros:
1. provide filteration.
2. provide sorting of columns on the basis of columns as well as sort as per the ascending or descending order.
3. provide pagination 
4. decent UI design
5. no need to bind data in html useing ng- for loop just pass json object in ts file where table initilises.

cons :  sorry still not found any cons

**Comment by codingfabi** [comment]
I implemented a Demo of the Child Table using http://valor-software.com/ng2-table/ into the childDetailFeature Branch.
It works except for the pagination-module.

**Comment by fschoell** [comment]
I'm objecting to the `ng2-table`, the last commit (and release) is from October last year, it's still depending on Angular 2 and there are 135 open issues and a lot of open pull requests (even though most of them are automated dependency upgrades). Doesn't look like an active project. Similar for `angular2-datatable` which is a bit more active, but again, the last activity is from May, it's still depending on Angular 2 and it seems to be a one man project. We shouldn't hold ourselfs up with possible 3rd party library bugs that won't get fixed or libraries not being adopted to newer Angular versions. 

I've found two active projects that might suit us:

* [ngx-datatable](https://github.com/swimlane/ngx-datatable): Not quite sure about the UI (they are using the material design, probably would need to adapt that), but it offers a lot of functionality and it seems to be very active.
* [ng2-smart-table](https://github.com/akveo/ng2-smart-table), which has a way better UI and a nice documentation. It should provide enough functionality for us, too (ngx-datatable might actually be a bit overloaded with features).

**Comment by codingfabi** [comment]
I would recommend using [ng2-smart-table](https://github.com/akveo/ng2-smart-table) as well 'cause it looks way better then [ngx-datatable](https://github.com/swimlane/ngx-datatable) and seems to provide every functionality we need.

[ngx-datatable](https://github.com/swimlane/ngx-datatable) is especially designed for presenting large and complex data (10k rows +) as they say on their GitHub page. We don't have to present those amount of rows (yet).

**Comment by aankitkumar31** [comment]
i would also recommend to use ng2-smart-table as we dont have large number of data

**Comment by sleidig** [comment]
Another alternative would be _Angular Material_ (https://material.angular.io/components/table/overview) that includes elements for UI tables and others like modal and datepicker.

Advantages:
- could replace multiple other libraries (ngx-bootstrap) and provide all UI elements out of one hand.
- made by the official Angular team

@NGO-DB/team what do you think? Anyone can post their experience on using any of the libraries yet?

**Comment by codingfabi** [comment]
Angular Material chosen
