### ISSUE TITLE
build scripts

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#8]
> **Developers need to merge and minify the whole project code.
> This process also needs to create an appcache.manifest file to make the app available offline.**

Things to consider:
- `npm start` seems to replace `grunt serve` during development?

What we need:
- [x] merge and minify the script files (`build` a version for deployment)
- [x] replace libraries with their minified version (and maybe use CDNs?)
- generate appcache.manifest: see #45
- ~~bump version and push to git~~ (can be added later if needed)

**Comment by fschoell** [comment]
We should take a look into [Angular CLI](https://github.com/angular/angular-cli) which is the official CLI for Angular 2. Unfortunately it's still work in progress.

**Comment by sebastian-leidig** [comment]
to build offline capable apps (with appcache.manifest) Angular CLI can be extended with [angular2-service-worker](https://github.com/angular/mobile-toolkit/blob/master/guides/service-worker.md)

**Comment by sebastian-leidig** [comment]
alternatively we could use [Angular 2 Seed App](https://github.com/mgechev/angular2-seed) which is using `gulp` and integrate [gulp-manifest](https://www.npmjs.com/package/gulp-manifest)

**Comment by fschoell** [comment]
I'm still a favorite of angular-cli. When I did some research for another project I read a lot of EmberJS vs Angular comparisons and the biggest argument for using EmberJS over Angular always has been ember-cli. As the angular-cli team are basing their software on ember-cli it could become equally powerful. And it has another big advantage, angular-cli is developed by the Angular team so we don't have to rely on third parties here (which gets us most likely better support in the long term). 

However, angular cli is still work in progress so it may not be the best idea to use it now. We could use the seed app for now and then switch to angular cli in the long term?

**Comment by fschoell** [comment]
I pushed a new branch where I adapted the project to angular-cli. This is not a working version currently, but you can use it to get an impression of the angular-cli tool and the project structure. The problem is that angular-cli recently (1-2 weeks ago) switched to webpack and this means there's nearly none documentation and still a lot of bugs. I would recommend to wait another couple of weeks if we are going to switch to angular-cli.

**Comment by sleidig** [comment]
with fb47a17  the project is now based on gulp for the time being and we have ready to use build scripts from [angular2-seed](https://github.com/mgechev/angular2-seed)

**Comment by fschoell** [comment]
Building the project doesn't seem to work correctly. `npm run build.dev` works, but the resulting `index.html` tries to include files from the `node_modules` folder which isn't available anymore. `npm run build.prod` is failing because of a missing file (`/dist/tmp/app/alerts/app/alerts/alerts.component.html`in my case, probably more of a general issue than actually a problem with this file).

**Comment by fschoell** [comment]
The problem with `build.prod` has been the template urls which resulted in a wrong path (`.../app/alerts/app/alerts/...`). I changed them to relative template urls within the components in 16efb9d. However, this requires `moduleId: module.id` to be set for each component. The build process is now working, but the final build is still faulty. There seems to be a problem with the css and js injection, as the paths in the `index.html` have a trailing slash although they are relative.

**Comment by sleidig** [comment]
The build is only working if deployed in the root of the web directory (any subdirectory like `localhost/ndb-core/` confused the filepaths) but then it is working nicely.


Also, the bootstrap glyphicon fonts are not found (but I don't think we are using them, as we have font-awesome):

> "NetworkError: 404 Not Found - http://localhost/fonts/glyphicons-halflings-regular.woff2"
glyphic...r.woff2
"NetworkError: 404 Not Found - http://localhost/fonts/glyphicons-halflings-regular.woff"
glyphic...ar.woff
"NetworkError: 404 Not Found - http://localhost/fonts/glyphicons-halflings-regular.ttf"
