### ISSUE TITLE
Use the live sync feature of PouchDB

### ISSUE THREAD

**Issue by fschoell** [NGO-DB/ndb-core#81]
Currently the database is only synced once to be notified when the sync has been completed. We should use the live sync however, which continously syncs the local database with the server. See PouchDB documentation on [replication](https://pouchdb.com/guides/replication.html).

**Comment by Lorsbyjm** [comment]
#122

**Comment by sleidig** [comment]
Can somebody confirm that it's actually not synced continuously? That would be a major issue as people often keep the app open for the whole day.

**Comment by fschoell** [comment]
Can't really test this currently, but it seems to be the case. The sync in [pouch-database-manager.service.ts](https://github.com/NGO-DB/ndb-core/blob/fb7123d2f3adfece9dab11b7b98431285ae1c31a/src/app/database/pouch-database-manager.service.ts) does only sync once. The reason behind this is that PouchDB does not emit any status messages when using the live feature and there are cases where we need to know when the sync has *completed* (for example to store the time of the last complete sync). 

I would say we use the promise in the `sync()` function in the PouchDatabaseManagerService and trigger a sync that sets `live` and `retry` on true (see [documentation](https://pouchdb.com/guides/replication.html#live%E2%80%93replication)), when the first, non-live sync has completed. 

I can't work on it currently, but maybe someone else can take over this. Should not be too hard, but we need a way to get both, regular confirmations about completed syncs, as well as continuous syncing.

**Comment by Lorsbyjm** [comment]
@fschoell which branch did you checked? Cause @liwde is currently working on the login an sync.

**Comment by fschoell** [comment]
I've checked the master branch. If anybody is already working on that, good.
