### ISSUE TITLE
Overview of pinned dependency versions and workarounds

### ISSUE THREAD

**Issue by fschoell** [NGO-DB/ndb-core#86]
Let's collect issues with dependencies upgrades here, so we have an overview which dependencies are pinned to a certain version and why and which workarounds are currently in place. 

 - ~~`pouchdb` and its typings are pinned to 6.1.1~~

**Comment by fschoell** [comment]
PouchDB 6.3.4 creates the following error: 
```
WARNING in ./src/app/database/pouch-database-manager.service.ts
42:0-14 "export 'plugin' (imported as 'PouchDB') was not found in 'pouchdb'
```

Might be a problem with pouchdb's types `@types/pouchdb` which are outdated (those are for the 6.1.1 version of pouchdb). We should wait with pouchdb updates until newer typings are released.

**Comment by sleidig** [comment]
Maybe better document this in a more visible/durable place - either in the README or the wiki?

**Comment by fschoell** [comment]
I think this is rather an "issue", as those are hopefully not pinned to a certain version forever. Just until the bugs are resolved by the 3rd party developers.

**Comment by sleidig** [comment]
closing this, as pouchdb is running on its latest version again
