### ISSUE TITLE
Move from bootstrap to angular material

### ISSUE THREAD

**Issue by fschoell** [NGO-DB/ndb-core#94]
Decided to use angular material rather than bootstrap as it offers more functionality nativly. ToDo:

- [x] Rewrite the basic site structure if neccessay (UI component)
- [x] Rewrite the navigation component
- [x] Rewrite the login component
- [x] Replace the AlertsComponent with Material Snackbars
- [x] Replace bootstrap modal of the LatestChanges component with Material Dialog
- [x] Replace all css styling based on bootstrap
- [x] Remove dependencies on bootstrap and ngx-bootstrap

**Comment by fschoell** [comment]
Created a `angular_material` branch with the current progress, see #93

**Comment by sleidig** [comment]
current work at #101
