### ISSUE TITLE
Clean up backlog of possibly outdated Pull Requests

### ISSUE THREAD

**Issue by sleidig** [NGO-DB/ndb-core#98]
Some of our [Pull Requests](https://github.com/NGO-DB/ndb-core/pulls) are open since almost a year and may well have become completely irrelevant. Let's clean this up so someone newly (re)joining the project - like me - has a chance of understanding the current state of the project.

Can someone also give a short overview of what the current roadmap looks like?

**Comment by sleidig** [comment]
@NGO-DB/team 
If we get #101 merged soon, I would suggest we delete any PR and branch that no one has worked on in recent weeks. current work towards angular material and the child and school modules is already included in #101.

**Comment by Lorsbyjm** [comment]
I deleted some of the outdated branches and closed the corresponding PRs, hopefully this is helpfull.

**Comment by sleidig** [comment]
thanks a lot. Looks much simpler now. The remaining ones all seem to have current issues related.

I think what's left now is only the duplication between `dev` and `preview` and possibly `master`. I would prefer using only a `master` branch in the future (after we sorted out the remaining stuff related to the three branches). A lot of github's default behaviour shows info in comparison to the default branch (our `master`).

What do you guys think?

**Comment by Lorsbyjm** [comment]
Yes, I agree with you.

**Comment by sleidig** [comment]
With the merge of `preview` into `master` (PR #101) and removal of `dev` and `preview` branches this is mostly done. Thanks!
